version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.27
    container_name: jaeger
    restart: on-failure
    networks:
    - tracing
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    restart: on-failure
    networks:
    - tracing
    ports:
    - "9090:9090"
    volumes:
    - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml

  server:
    image: jaeger-server
    container_name: server
    restart: on-failure
    networks:
    - tracing
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
    - "8080:8080"
    environment:
    - JAEGER_SERVICE_NAME=server
    - JAEGER_AGENT_HOST=jaeger
    - JAEGER_AGENT_PORT=6831
    - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:6831
    - JAEGER_REPORTER_LOG_SPANS=true
    - JAEGER_SAMPLER_PARAM=1
    - JAEGER_SAMPLER_TYPE=const
    - JAEGER_RPC_METRICS=true
    depends_on:
    - jaeger

networks:
  tracing:
    name: tracing